name: build(cmake)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
    inputs:
      version:
        default: 'latest'
        description: 'Package version'
        type: string
        required: true
      run_test:
        description: 'Run Test ?'
        required: true
        type: boolean
        default: true

  schedule:
    - cron: '0 20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get Version
        run: |
          if [ "${{ github.event_name }}" = "schedule" ] || [ "${{ inputs.version }}" = "latest" ]; then
            version=$(curl -s "https://api.github.com/repos/Kitware/CMake/releases/latest" | jq -r .tag_name)
          else
            version=${{ inputs.version }}
          fi
          if [ -z "${version}" ] || [ "${version}" == "null" ]; then
            echo "Failed to get version"
            exit 1
          fi

          echo "version=${version}" >> $GITHUB_ENV
          echo ""
          echo "========== Build Args =========="
          echo "version=${version}"

      - name: Check Release
        run: |
          gh release view ${version} -R ${{ github.repository }} | grep cmake-.*-linux-loongarch64.tar.gz >/dev/null 2>&1 || echo "build=1" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout code
        if: env.build == 1
        uses: actions/checkout@v5

      - name: Setup QEMU
        if: env.build == 1
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: env.build == 1
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        if: env.build == 1
        uses: docker/build-push-action@v6
        with:
          context: Utilities/Release/linux/loongarch64
          platforms: linux/loong64
          load: true
          push: false
          build-args: |
            VERSION=${{ env.version }}
            TEST=${{ inputs.run_test }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/kitware/cmake:${{ env.version }}
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Create Tag
        if: env.build == 1
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "Release ${app_version}" || true
          git tag ${app_version}
          git push origin ${app_version}  || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Binaries
        if: env.build == 1
        run: |
          mkdir -p dist
          docker run --rm \
            -v $(pwd)/dist:/dist \
            ghcr.io/${{ github.repository_owner }}/kitware/cmake:${version} \
            bash -c 'cp -f /out/* /dist/'

          cd dist
          sha256sum cmake-* > cmake-${version/v/}-SHA-256.txt

      - name: Create Release
        if: env.build == 1
        run: |
          gh release create ${version} -R ${{ github.repository }} --title ${version} --notes "**Full Changelog**: [${version}](https://github.com/Kitware/CMake/releases/tag/${version})"
          gh release upload ${version} -R ${{ github.repository }} dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          